[XAM] Improve XamUserIsUnsafeProgrammingAllowed Stub
xenia-canary/xenia-canary pull request #421
Opened 2024-11-19 00:01 UTC by AdrianCassar

2024-11-19 19:35 UTC, Pipi86 commented on src/xenia/kernel/xam/xam_user.cc
> +                                                       dword_t ukn,
```suggestion
                                                       dword_t unk,
```

2024-11-19 19:39 UTC, Pipi86 requested changes

2024-11-19 19:39 UTC, Pipi86 commented on src/xenia/kernel/xam/xam_user.cc
> +                                                       dword_t ukn,
```suggestion
                                                       dword_t unk,
```

2024-11-24 09:50 UTC, Gliniak commented on src/xenia/kernel/xam/xam_user.cc
> +  if (!result_ptr ||
I would split this check into separate entry for lack of result pointer and incorrect user_index. That way it will be less confusing to read

2024-11-25 07:48 UTC, merged